name: reserva_de_canchas
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  syncfusion_flutter_datepicker: ^24.2.6
  image_picker: ^1.0.7
  cached_network_image: ^3.2.1
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.1.0
  pull_to_refresh: ^2.0.0
  intl: ^0.19.0

dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
